version: "3"

services:
  pclink:
    image: pclink:0.3.0-alpha
    restart: on-failure
    environment:
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SECRET_KEY
    volumes:
      - .:/pclink
      - static-volume:/home/ubuntu/static/
      - media-volume:/home/ubuntu/media/
    depends_on:
      - db

  db:
    image: mariadb:10.4
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - mariadb-database:/var/lib/mysql

volumes:
  mariadb-database:
  static-volume:
  media-volume: