version: "3"

services:
  pclink:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    image: pclink:0.3.0-alpha
    restart: on-failure
    environment:
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_EMAIL
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SECRET_KEY
    volumes:
      - .:/pclink
      - static-volume:/home/ubuntu/static/
      - media-volume:/home/ubuntu/media/
    command: sh start.sh
    depends_on:
      - db

  webserver:
    image: nginx:1
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./pclink.conf:/etc/nginx/conf.d/pclink.conf:ro
      - static-volume:/home/ubuntu/static/
      - media-volume:/home/ubuntu/media/
    command: nginx -g "daemon off;"
    depends_on:
      - pclink
      - db

  db:
    image: mariadb:10.4
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - mariadb-database:/var/lib/mysql

volumes:
  mariadb-database:
  static-volume:
  media-volume: