# Generated by Django 3.1.6 on 2021-03-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_calculator', '0003_auto_20210330_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programoutcomeresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='period_order_value',
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('active',), name='unique_active'),
        ),
    ]
