# Generated by Django 3.1.6 on 2021-03-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_calculator', '0004_auto_20210331_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programoutcomeresult',
            options={'ordering': ['course']},
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_active',
        ),
        migrations.AddField(
            model_name='semester',
            name='period_order_value',
            field=models.IntegerField(default=1),
        ),
    ]
